theme: jekyll-theme-minimal
google_analytics: UA-158047400-1
show_downloads: "false"
logo: /assets/logo_github.png
markdown: kramdown
github:
  is_project_page: true
  repository_url: https://github.com/RadioNinjaPirata/radioninjapirata.github.io
  repository_name: RadioNinjaPirata
  owner_url: https://github.com/RadioNinjaPirata
  owner_name: RadioNinjaPirata
